name: Release

on:
  push:
    branches: [main, dev]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  docker:
    strategy:
      fail-fast: false
      matrix:
        arch:
          [
            [x86_64-unknown-linux-gnu, linux/amd64],
            [aarch64-unknown-linux-gnu, linux/arm64/v8],
          ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3

      - name: Setup Rust toolchain
        id: rust
        run: |
          rustup toolchain install stable --profile minimal
          rustup default stable
          rustup target add ${{ matrix.arch[0] }}

      - name: Setup Rust Cache
        id: rust-cache
        uses: Swatinem/rust-cache@v2

      - name: Build
        id: rust_build
        run: cargo build --release --target=${{ matrix.arch[0] }}

      - name: Setup QEMU
        id: qemu
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        id: login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Image and Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: ${{ matrix.arch[1] }}
          cache-to: type=gha,mode=max,ignore-error=true
          cache-from: type=gha
          push: true
          tags: revanced/revanced-discord-bot:latest
