name: Release

on:
  push:
    branches: [main, dev]

  pull_request:

  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt install libleptonica-dev libtesseract-dev libssl-dev

      - name: Setup Rust toolchain
        id: rust-toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: clippy

      - name: Cache
        uses: actions/cache@v3
        id: cache
        with:
          path: |
            ~/.cargo/registry/cache/
            target/
          key: ${{ steps.rust-toolchain.outputs.rustc_hash }}-${{ hashFiles('**/Cargo.lock') }}

      - name: cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
          use-cross: true

      - name: cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --no-deps -- -D warnings

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: revanced-discord-bot
          path: target/release/revanced-discord-bot

      - name: Setup semantic-release
        if: github.event_name != 'pull_request'
        run: npm install -g semantic-release @semantic-release/git @semantic-release/changelog -D

      - name: Release
        if: github.event_name != 'pull_request'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
