name: Release

on:
  push:
    branches: [main, dev]

  pull_request:

  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "latest"

      - name: Setup Rust toolchain
        id: rust-toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: clippy

      - name: Set up cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: "true"

      - name: cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --no-deps -- -D warnings

      - name: cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target=x86_64-unknown-linux-musl
          use-cross: true

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: revanced-discord-bot
          path: target/x86_64-unknown-linux-musl/release/revanced-discord-bot

      - name: Setup semantic-release
        if: github.event_name != 'pull_request'
        run: npm install -g semantic-release @semantic-release/git @semantic-release/changelog -D

      - name: Release
        if: github.event_name != 'pull_request'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
